### ISSUE TITLE
Azure Search API Version

### ISSUE THREAD

**Issue by mquekel** [Masahigo/sitecore-azure-devops#1]
Hello,

We are using the Azure Devops Scripts for our continous deployment with VSTS to Azure.

After deployment I noticed that there an error in the log that appeared several times.
I found out that this issue was caused by an incorrect connectionstring.
This connectionstring is created by the following line in the extract-params-xp.ps1 file:
`$CloudSearchConnString = "serviceUrl=https://$SearchServiceName.search.windows.net;apiVersion=2015-02-28;apiKey=$SearchApiKey"`

The version that is used: `2015-02-28` is incorrect and should be replaced by `2015-02-28-Preview`
Also see https://kb.sitecore.net/articles/549969 

Kind regards,
Martijn Quekel

**Comment by Masahigo** [comment]
Hi Martijn,

Thanks a lot, I had missed that 👍 

Masi
